### ISSUE TITLE
Title Writing not working

### ISSUE THREAD

**Issue by kashyapkumbhani** [maximedrn/pinterest-automatic-upload#13]
Image upload is working fine but 
after that when its comes to title its showing this error 

Uploading pins n°1/1. Failed. Message:
Stacktrace:
        GetHandleVerifier [0x00566E73+174291]
        (No symbol) [0x00490AC1]
        (No symbol) [0x001A6FF6]
        (No symbol) [0x001D9876]
        (No symbol) [0x001D9C2C]
        (No symbol) [0x0020BD42]
        (No symbol) [0x001F7054]
        (No symbol) [0x0020A104]
        (No symbol) [0x001F6DA6]
        (No symbol) [0x001D1034]
        (No symbol) [0x001D1F8D]
        GetHandleVerifier [0x006049CC+820268]
        sqlite3_dbdata_init [0x006C4EBE+652494]
        sqlite3_dbdata_init [0x006C48D9+650985]
        sqlite3_dbdata_init [0x006B962C+605244]
        sqlite3_dbdata_init [0x006C586B+654971]
        (No symbol) [0x0049FEBC]
        (No symbol) [0x00498428]
        (No symbol) [0x0049854D]
        (No symbol) [0x00485858]
        BaseThreadInitThunk [0x75757BA9+25]
        RtlInitializeExceptionChain [0x7738BD2B+107]
        RtlClearBits [0x7738BCAF+191]
        (No symbol) [0x00000000]

**Comment by melwin2001** [comment]
Did you fix it
