### ISSUE TITLE
not respond upload image from path source..why?

### ISSUE THREAD

**Issue by gatekendo** [maximedrn/pinterest-automatic-upload#3]
https://user-images.githubusercontent.com/78825059/148652591-b6c9ef62-fe1a-4d23-a479-706b6d935106.mp4

**Comment by gatekendo** [comment]
https://user-images.githubusercontent.com/78825059/148652569-ec45c52c-9eeb-44c4-989a-91492ab4b1d1.mp4

**Comment by gatekendo** [comment]
![image](https://user-images.githubusercontent.com/78825059/148652799-779f97e5-af78-4aaa-99d8-54469c4f8766.png)

**Comment by gatekendo** [comment]
{
  "pin": [
    {
      "pinboard": "kitchen",
      "file_path": "C:/Users/admin/Desktop/images/1.png",
      "title": "My Pin",
      "description": "This is my pin",
      "alt_text": "A beautiful dog",
      "link": "",
      "date": ""
    },
    {
      "pinboard": "kitchen",
      "file_path": "C:/Users/admin/Desktop/images/2.png",
      "title": "My Pin",
      "description": "This is my pin",
      "alt_text": "A beautiful dog",
      "link": "",
      "date": ""
    },
    {
      "pinboard": "kitchen",
      "file_path": "C:/Users/admin/Desktop/images/2.png",
      "title": "My Pin",
      "description": "This is my pin",
      "alt_text": "A beautiful dog",
      "link": "",
      "date": ""
    }
  ]
}

**Comment by maximedrn** [comment]
The problem comes from the Pinboard, I have to update the bot because the Pinboard part is not working.
Your data file is correct by the way.

**Comment by rpgraul** [comment]
Hi @maximedrn , did you solve the Pinboard problem already? Thnks ;)

**Comment by benx13** [comment]
@rpgraul did you find a solution?

**Comment by rpgraul** [comment]
@benx13 sorry, no solution yet :/
